[package]
name = "blt-dl"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "3.0.5"
scraper = "0.13.0"
url = "2.5.4"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
